[2025-06-20T21:41:06.671+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-20T21:41:06.688+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag.dbt_run manual__2025-06-20T21:36:01.553737+00:00 [queued]>
[2025-06-20T21:41:06.698+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag.dbt_run manual__2025-06-20T21:36:01.553737+00:00 [queued]>
[2025-06-20T21:41:06.699+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-06-20T21:41:06.747+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): dbt_run> on 2025-06-20 21:36:01.553737+00:00
[2025-06-20T21:41:06.754+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=278) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-20T21:41:06.756+0000] {standard_task_runner.py:72} INFO - Started process 280 to run task
[2025-06-20T21:41:06.757+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag', 'dbt_run', 'manual__2025-06-20T21:36:01.553737+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpnpz7948i']
[2025-06-20T21:41:06.758+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask dbt_run
[2025-06-20T21:41:06.820+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_dag.dbt_run manual__2025-06-20T21:36:01.553737+00:00 [running]> on host 63f149901e14
[2025-06-20T21:41:06.909+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_dag' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-06-20T21:36:01.553737+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-20T21:36:01.553737+00:00'
[2025-06-20T21:41:06.910+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-06-20T21:41:06.911+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-06-20T21:41:06.911+0000] {logging_mixin.py:190} INFO - Current task name:dbt_run state:running start_date:2025-06-20 21:41:06.689658+00:00
[2025-06-20T21:41:06.912+0000] {logging_mixin.py:190} INFO - Dag name:dbt_dag and current dag run status:running
[2025-06-20T21:41:06.913+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-20T21:41:06.914+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-06-20T21:41:06.915+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/snowflake_data_pr && dbt run']
[2025-06-20T21:41:06.931+0000] {subprocess.py:99} INFO - Output:
[2025-06-20T21:41:06.933+0000] {subprocess.py:106} INFO - /usr/bin/bash: line 1: cd: /opt/***/snowflake_data_pr: No such file or directory
[2025-06-20T21:41:06.933+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-06-20T21:41:06.944+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-20T21:41:06.950+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-06-20T21:41:06.950+0000] {logging_mixin.py:190} INFO - Task start:2025-06-20 21:41:06.689658+00:00 end:2025-06-20 21:41:06.949589+00:00 duration:0.259931
[2025-06-20T21:41:06.951+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): dbt_run> dag:<DAG: dbt_dag> dagrun:<DagRun dbt_dag @ 2025-06-20 21:36:01.553737+00:00: manual__2025-06-20T21:36:01.553737+00:00, state:running, queued_at: 2025-06-20 21:36:01.573960+00:00. externally triggered: True>
[2025-06-20T21:41:06.951+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 1.
[2025-06-20T21:41:06.952+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dbt_dag, task_id=dbt_run, run_id=manual__2025-06-20T21:36:01.553737+00:00, execution_date=20250620T213601, start_date=20250620T214106, end_date=20250620T214106
[2025-06-20T21:41:06.970+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-20T21:41:06.971+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 8 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 280)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-20T21:41:07.011+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-20T21:41:07.034+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-20T21:41:07.043+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
